-- Seed IPC <-> BNS section mapping (selected high-value entries).
-- Full mapping shipped via scripts/load_ipc_bns_mapping.py from authoritative public source.
-- BNS came into force 1 July 2024.

insert into statute_section_mapping (old_act, old_section, new_act, new_section, notes) values
 ('IPC','299','BNS','100','Culpable homicide'),
 ('IPC','300','BNS','101','Murder'),
 ('IPC','302','BNS','103','Punishment for murder'),
 ('IPC','304','BNS','105','Culpable homicide not amounting to murder'),
 ('IPC','304A','BNS','106','Causing death by negligence'),
 ('IPC','304B','BNS','80','Dowry death'),
 ('IPC','307','BNS','109','Attempt to murder'),
 ('IPC','323','BNS','115(2)','Voluntarily causing hurt'),
 ('IPC','324','BNS','118(1)','Voluntarily causing hurt by dangerous weapons'),
 ('IPC','325','BNS','117(2)','Voluntarily causing grievous hurt'),
 ('IPC','354','BNS','74','Assault on woman with intent to outrage modesty'),
 ('IPC','354A','BNS','75','Sexual harassment'),
 ('IPC','354B','BNS','76','Assault to disrobe'),
 ('IPC','354C','BNS','77','Voyeurism'),
 ('IPC','354D','BNS','78','Stalking'),
 ('IPC','375','BNS','63','Rape (definition)'),
 ('IPC','376','BNS','64','Punishment for rape'),
 ('IPC','376A','BNS','66','Death/PVS due to rape'),
 ('IPC','376B','BNS','67','Sexual intercourse by spouse during separation'),
 ('IPC','376D','BNS','70','Gang rape'),
 ('IPC','379','BNS','303(2)','Theft'),
 ('IPC','380','BNS','305','Theft in dwelling'),
 ('IPC','392','BNS','309(4)','Robbery'),
 ('IPC','395','BNS','310(2)','Dacoity'),
 ('IPC','405','BNS','316(1)','Criminal breach of trust (definition)'),
 ('IPC','406','BNS','316(2)','Criminal breach of trust (punishment)'),
 ('IPC','415','BNS','318(1)','Cheating (definition)'),
 ('IPC','420','BNS','318(4)','Cheating and dishonestly inducing delivery'),
 ('IPC','463','BNS','336(1)','Forgery (definition)'),
 ('IPC','464','BNS','335','Making a false document'),
 ('IPC','468','BNS','336(3)','Forgery for purpose of cheating'),
 ('IPC','471','BNS','340(2)','Using a forged document as genuine'),
 ('IPC','494','BNS','82','Bigamy'),
 ('IPC','498A','BNS','85','Cruelty by husband or relatives'),
 ('IPC','499','BNS','356(1)','Defamation (definition)'),
 ('IPC','500','BNS','356(2)','Punishment for defamation'),
 ('IPC','503','BNS','351(1)','Criminal intimidation (definition)'),
 ('IPC','506','BNS','351(2)/(3)','Punishment for criminal intimidation'),
 ('IPC','509','BNS','79','Word/gesture intended to insult modesty of woman'),
 ('CrPC','41','BNSS','35','Arrest without warrant'),
 ('CrPC','154','BNSS','173','FIR'),
 ('CrPC','156','BNSS','175','Police investigation'),
 ('CrPC','161','BNSS','180','Examination of witnesses by police'),
 ('CrPC','164','BNSS','183','Recording of confessions and statements'),
 ('CrPC','167','BNSS','187','Detention beyond 24 hours'),
 ('CrPC','173','BNSS','193','Police report on completion of investigation'),
 ('CrPC','190','BNSS','210','Cognizance of offences by Magistrates'),
 ('CrPC','200','BNSS','223','Examination of complainant'),
 ('CrPC','436A','BNSS','479','Maximum period of detention as undertrial'),
 ('CrPC','438','BNSS','482','Anticipatory bail'),
 ('CrPC','439','BNSS','483','Special powers of HC/Sessions on bail'),
 ('Indian Evidence Act','3','BSA','2','Definitions'),
 ('Indian Evidence Act','17','BSA','15','Admission'),
 ('Indian Evidence Act','24','BSA','22','Confession by inducement'),
 ('Indian Evidence Act','25','BSA','23(1)','Confession to police inadmissible'),
 ('Indian Evidence Act','27','BSA','23(2)','Information leading to discovery'),
 ('Indian Evidence Act','45','BSA','39','Opinion of experts'),
 ('Indian Evidence Act','65A','BSA','62','Special provisions for electronic evidence'),
 ('Indian Evidence Act','65B','BSA','63','Admissibility of electronic records')
on conflict do nothing;
